### ISSUE TITLE
Adding punishment points ignores previous points

### ISSUE THREAD

**Issue by Fiskepuddingen** [GodDragoner/Spicy-TAJ-Personality#46]
AddPunishmentPointsDirectly seems to add the multiplied points to the base amount.
I.E. Adding 10 points with a multiplier of 3 will set your points to 40, regardless of the initial value

https://github.com/GodDragoner/Spicy-TAJ-Personality/blob/e5aadf4dc4a81ee314e28e86318cb67ca57e4ba3/Slaves/Slave.js#L220

Log excerpt:

> 02:44:49 a.m. CHAT: 02:44 a.m. T: Points?
02:44:49 a.m. CHAT: [Miss A]: Let me just check my computer...
02:44:50 a.m. CHAT: [Miss A]: According to my records you have 240 punishment points.
02:44:53 a.m. INFO: About to add 32 punishment points
02:44:53 a.m. INFO: Base pp multiplier is 3
02:44:53 a.m. INFO: Calculating mood for 888 and strictness 1
02:44:53 a.m. INFO: Hours since last pp multiplier change 0
02:44:53 a.m. INFO: Base multiplier level is 1.1
02:44:53 a.m. INFO: Subtract multiplier level is 0
02:44:53 a.m. INFO: New pp multiplier is 3
02:44:53 a.m. INFO: Adding (with multiplier) 96 punishment points
02:44:53 a.m. INFO: Reason was -1
02:44:53 a.m. CHAT: [Miss A]: Hey, while I have this file open let me add a few more
02:44:55 a.m. INFO: Calculating mood for 888 and strictness 1
02:44:55 a.m. CHAT: [Miss A]: Sissy, you're welcome
02:44:57 a.m. CHAT: [Miss A]: Only a little punishment will be needed
02:44:59 a.m. INFO: Calculating mood for 888 and strictness 1
02:44:59 a.m. CHAT: [Miss A]: Yes cock hungry cum lover?
02:45:03 a.m. CHAT: 02:45 a.m. T: Points?
02:45:03 a.m. INFO: Calculating mood for 888 and strictness 1
02:45:03 a.m. CHAT: [Miss A]: 2 seconds stroker
02:45:04 a.m. CHAT: [Miss A]: According to my records you have 128 punishment points.

**Comment by GodDragoner** [comment]
Fixed in 856cfcc99700239aff48c0433dfd543cfd17a0b1
