### ISSUE TITLE
Image names

### ISSUE THREAD

**Issue by Machine-Maker** [GodDragoner/Spicy-TAJ-Personality#8]
So there are a couple image names that are off, the image set I have has a couple .JPG instead of .jpg and the toy image names are off from what Setup.js uses. Are you using an updated image set? And if so, should I not worry about changing the names in the various files?

**Comment by GodDragoner** [comment]
Sorry for the late response. Just saw it. Yes I am using updated images and video paths because I am gonna remove unneccessary stuff and sort it. Then I am gonna release new sets of sounds and audio.
